### ISSUE TITLE
bsddb.db.DBRunRecoveryError

### ISSUE THREAD

**Issue by ralphholz** [andreasscherbaum/maildir2gmail#6]
Hi - thanks for a good piece of software that has the potential to help me migrate my mail.

I do run into this error quite frequently now - after maybe sending 3k mails. It seems to be a DB corruption, but I am not entirely sure where to look:

bsddb.db.DBRunRecoveryError: (-30973, 'BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery -- BDB0061 PANIC: Invalid argument')
Exception bsddb.db.DBRunRecoveryError: DBRunRecoveryError(-30973, 'BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery -- BDB0060 PANIC: fatal region error detected; run recovery') in  ignored
Exception bsddb.db.DBRunRecoveryError: DBRunRecoveryError(-30973, 'BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery -- BDB0060 PANIC: fatal region error detected; run recovery') in  ignored

**Comment by ralphholz** [comment]
Tracking this a bit, it seems to be used by shelve.

**Comment by ralphholz** [comment]
And even more - could it be that shelve creates some file that is not unique to the current execution? I.e. if I have two maildirs that I am trying to upload simultaneously, it will corrupt that file?

**Comment by ralphholz** [comment]
Confirmed: the file is $GITHUBREPOPATH/maildir2gmail.

This file should get a unique name to avoid this problem - but I think you want to persist it, right, so a random filename is out of the question as you need to load it on the next instantiation? You could make it an argument via argparse.

Alternative 1: exit to shell if file already exists to avoid corruption.

Alternative 2: say in the docs that running two concurrent instances of maildir2gmail is not safe. :)

**Comment by andreasscherbaum** [comment]
Two concurrent instances would be two separate directories. maildir2gmail has to store the data somewhere, and if you don't specify any path, obviously it will be somewhere where the instance can find it all the time. Either your home, or in the current directory.

If you plan to amend the README, please submit a PR.
